name: Check URLs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check URLs
        uses: paramt/url-checker@master
        with:
          files: "test.md"
          blacklist: "https://www.github.com/paramt/url-that-does-not-exist"
